name: Scrape

on:
  push:
  workflow_dispatch:
  schedule:
  # Daily at 6:26 AM UTC
  - cron: '26 6 * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Set up Python
      run: uv python install 3.13
    - name: Run scraper
      run: |
        uv run --with click --with beautifulsoup4 --with requests --with lxml python scrape_anthropic_blog.py 'https://www.anthropic.com/engineering'
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
